### PR TITLE
CSCFAIRADM-312 Custom pre-commit hook & git-secrets

### PR DESCRIPTION
**Pull request by EarthModule**

### CODE REVIEW

**Comment by MattiasLevlin** [comment]
This PR requires reviewed documentation of how to use the new deployment process (including handling of git secrets) before it can be merged.

**Comment by EarthModule** [comment]
Documentation can be found here: https://wiki.csc.fi/FairdataAdm/GitSecrets

**Comment by MattiasLevlin** [comment]
The documentation looks good in itself and using git secrets would probably be an improvement. However, this PR is in a sense slightly less secure, since it exposes the path and names of the non-production secret files and the name of the non-production SSH keys (in the file .gitsecret.dev/paths/mapping.cfg).

Berfore merging, I think this requires some coordination and review on a broader level and then discussion whether or not to implement it in Metax as well (where it is most needed, in my opinion). This because it alters how development and deployment processes are handled. 

Currently, Etsin and Metax handle secrets in the same way, and if the process is changed, it should be changed in both services.

**Comment by MattiasLevlin** [comment]
Closing as out-of-date, secret configurations have been replaced by other tools/repositories.

**Pull request closed without merging**
