### PR TITLE
CSCFAIRMETA-399: local development build environment speed improvement.

### PR DESCRIPTION
**Pull request by jppiiroinen**
Improved build time from ~26 mins to less than 10 mins.
Added scripts for building custom vagrant box for local_development.

### CODE REVIEW

**Comment by jppiiroinen** [comment]
Related documentation for Vagrant custom boxes:
https://www.vagrantup.com/docs/virtualbox/boxes.html
https://www.vagrantup.com/docs/boxes/base.html

**Review by kasperkeinanen — APPROVED** [review]
Can confirm that compared to CSCFAIRMETA-326 the build was almost twice as fast, 10min vs 19min (the build was measured to the point where: TASK [frontend : Run frontend dev build for local development environment] )

Good idea to start using the basebox faircentos.

**Comment by jppiiroinen** [comment]
Fixed merge conflict by rebase via command line.

**Comment by jppiiroinen** [comment]
Fixed a bug which would have impacted production:
```
diff --git a/ansible/roles/os-base/tasks/main.yml b/ansible/roles/os-base/tasks/main.yml
index 81b2efa..56f32a7 100644
--- a/ansible/roles/os-base/tasks/main.yml
+++ b/ansible/roles/os-base/tasks/main.yml
@@ -27,11 +27,11 @@
           - python-passlib
           - python-pip
           - python-virtualenv
+          - rng-tools
         yum_dev_packages: 
           - htop
           - ntp
           - tree
-          - rng-tools
     - set_fact:
         yum_packages: "{{ yum_packages + yum_dev_packages }}"
       when: deployment_environment_id not in ['staging', 'production']
```

**Pull request merged**
